add-highlighter global/ number-lines
add-highlighter global/wrap wrap
set global tabstop 4
set global indentwidth 4
map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'
map global insert <c-tab> '<tab>'
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

map global user y '<a-|>xsel -i -b<ret>'
